### ISSUE TITLE
Require Example

### ISSUE THREAD

**Issue by LondonWebFactory** [maximilianMairinger/getBaseUrl#3]
Great extension! Definitely an important issue.

Is there any chance you could add a require example though. 

`const getBaseUrl = require('get-base-url')`

When I run the above I get an error.

Many thanks.

**Comment by maximilianMairinger** [comment]
Sorry for the late answere. I agree, it should simply work with require, but it doesnt. I have really tried to offer multiple builds dependent on the import statement but it doesnt work the way I want it to. I wont go into detail of why it cannot "just work", just note that nodejs imports are a mess, as you cant use cjs `require` **and** `esm` imports within one script. As it is, I do not want to throw away the benefits of exporting a esm module (tree shaking for the browser) just for compatebility reasons. 

To solve your problem I would heavily recommend to setup a bundler that compiles all different import syntaxes of your dependencies into one format. Which would also have the benefit of enabeling the use of typescript and other transpiled languages.

As a bundler I would recommend [rollup](http://rollupjs.org/). [Here](https://github.com/maximilianMairinger/keyIndex/blob/master/rollup.web.common.config.js) is a config that I use in one of my projects (as a working example). If you need any help with setting up your build infrastructure, please let me know. I am happy to help.

**Comment by maximilianMairinger** [comment]
Actually I am just dumb, what I was trying is actually working. I just had a typo. Will fix soon. Thanks for the issue :)

**Comment by maximilianMairinger** [comment]
Working in 2.2.0
